#!/usr/bin/env bash
echo ""
echo "    bootstrap packrat and restore dependencies..."
echo ""
if [ -f .Rprofile ]; then
   mv .Rprofile .Rprofile2
fi
Rscript packrat/init.R --bootstrap-packrat
R -q -e "packrat::snapshot()"
if [ -f .Rprofile2 ]; then
   mv .Rprofile2 .Rprofile
fi
echo ""
echo "    finished bootstraping packrat ... all done..."
echo ""
