#!/usr/bin/env bash
echo ""
echo "    remove existing version of maxplanckr..."
echo ""
R -q -e 'packrat::clean("maxplanckr", force=T)'
echo ""
echo "    install maxplanckr from github repository..."
echo ""
if [ -f .Rprofile ]; then
   mv .Rprofile .Rprofile2
fi
R -q -e 'source("packrat/init.R");devtools::install_github("herreio/maxplanckr")'
echo ""
echo "    create snapshot of library with packrat..."
echo ""
R -q -e 'packrat::snapshot()'
if [ -f .Rprofile2 ]; then
   mv .Rprofile2 .Rprofile
fi
echo ""
echo "    all done..."
echo ""
